# Generated by Django 4.2.6 on 2023-11-02 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album', models.CharField(max_length=30)),
                ('Lyrics', models.DateField()),
                ('Duration', models.CharField(max_length=30)),
                ('Rating', models.CharField(max_length=30)),
                ('Notes', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='class_school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('number_school', models.CharField(max_length=30)),
                ('number_class', models.IntegerField()),
                ('leter_class', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surnmae', models.CharField(max_length=30)),
                ('dateofbirth', models.DateField(max_length=100)),
                ('gmail', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('create_att', models.DateTimeField(auto_now_add=True)),
                ('modified_att', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='I',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('gmail', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Instrument', models.DateField()),
                ('Genre', models.CharField(max_length=30)),
                ('Birthdate', models.CharField(max_length=30)),
                ('Biography', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='My_school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_school', models.CharField(max_length=30)),
                ('number_school', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('create_att', models.DateField()),
                ('dg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Reyka.dg')),
            ],
        ),
    ]
