# Generated by Django 4.2.6 on 2023-11-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_Reyka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=30)),
                ('level', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_task', models.CharField(max_length=30)),
                ('create_att', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('deadline', models.DateField()),
                ('project_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Reyka.project')),
            ],
        ),
    ]
