# Generated by Django 4.2.6 on 2023-11-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Reyka', '0002_project_project_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='level',
            field=models.IntegerField(),
        ),
    ]
