# Generated by Django 4.2.6 on 2023-11-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Reyka', '0004_card_dostup_group_library_literatura_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_task',
            name='create_att',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
