# Generated by Django 4.2.6 on 2023-11-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Reyka', '0005_alter_project_task_create_att'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name_project',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='project_task',
            old_name='text_task',
            new_name='text',
        ),
    ]
